export const colors = {
  background: '#F7F8FA',
  appBackground: '#EEF7FF',
  userSelectBackground: '#F7F8FA',
  panel: '#FFFFFF',
  text: '#172033',
  muted: '#6B7280',
  border: '#D7DCE7',
  active: '#E5F2ED',
  activeText: '#1F7A4D',
  primary: '#1F7A4D',
  destructive: '#C94B4B',
  errorBackground: '#FEF3F2',
  destructiveBorder: '#C94B4B',
} as const;
