export const strings = {
  app: {
    title: 'GymBro',
  },
  tabs: {
    machines: 'Тренажеры',
    workouts: 'Тренировки',
  },
  search: {
    machines: 'Поиск тренажера',
    workouts: 'Поиск тренировки',
  },
  empty: {
    machines: {
      title: 'Тренажеров пока нет',
      message: 'Здесь появятся тренажеры, которые ты добавишь для своих занятий.',
    },
    workouts: {
      title: 'Тренировок пока нет',
      message: 'Нажми кнопку внизу, чтобы начать первую тренировку в зале.',
    },
    filtered: {
      title: 'Ничего не найдено',
      message: 'Попробуй изменить запрос или сбросить поиск.',
    },
  },
  actions: {
    cancel: 'Отмена',
    addIcon: '+',
    delete: 'Удалить',
    deleteIcon: '×',
    dontSave: 'Не сохранять',
    editIcon: '✎',
    finish: 'Завершить',
    ok: 'ОК',
    resetSearch: 'Сбросить поиск',
    save: 'Сохранить',
  },
  settings: {
    changeUser: 'Сменить',
    currentUser: 'Пользователь',
    noUser: 'Не выбран',
    title: 'Настройки',
  },
  users: {
    selectMessage: 'Выбери, чьи тренировки показывать на этом телефоне.',
    selectTitle: 'Кто тренируется?',
    selectUser: (name: string) => `Выбрать пользователя ${name}`,
  },
  alerts: {
    deleteMachineTitle: 'Удалить тренажер?',
    deleteMachineMessage: (name: string) =>
      `Тренажер «${name}» будет удален из списка.`,
    deleteWorkoutTitle: 'Удалить тренировку?',
    deleteWorkoutMessage: (name: string) =>
      `Тренировка «${name}» будет удалена из списка.`,
    exitWorkoutTitle: 'Сохранить тренировку?',
    exitWorkoutMessage: 'Перед выходом можно сохранить введенные подходы.',
    storageLoadTitle: 'Не удалось загрузить данные',
    storageLoadMessage: 'Проверь подключение к интернету и попробуй еще раз.',
    storageSaveTitle: 'Не удалось сохранить данные',
    storageSaveMessage: 'Проверь подключение к интернету и попробуй снова.',
    userSaveTitle: 'Не удалось запомнить пользователя',
    userSaveMessage:
      'Выбор применен сейчас, но может не сохраниться после перезапуска приложения.',
  },
  forms: {
    machine: {
      addTitle: 'Новый тренажер',
      editTitle: 'Редактировать тренажер',
      nameLabel: 'Название',
      namePlaceholder: 'Например, жим ногами',
      muscleGroupLabel: 'Группы мышц',
      muscleGroupHint: 'Выбери одну или несколько групп.',
      noteLabel: 'Заметка',
      notePlaceholder: 'Посадка, настройки, важные ощущения',
      errors: {
        nameRequired: 'Введите название тренажера.',
      },
    },
    workout: {
      nameLabel: 'Название',
      namePlaceholder: 'Например, Тренировка ног',
    },
  },
  workouts: {
    addExerciseTitle: 'Добавить тренажер',
    addMachineToWorkout: (name: string) => `Добавить ${name} в тренировку`,
    addSet: 'Добавить подход',
    cardMeta: (exerciseCount: number, setCount: number) =>
      `${exerciseCount} упр. · ${setCount} подх.`,
    clearExerciseSets: 'Очистить подходы',
    collapseExercise: 'Свернуть тренажер',
    defaultName: 'Тренировка',
    defaultNameWithDate: (date: string) => `Тренировка ${date}`,
    deleteExercise: 'Удалить упражнение',
    deleteSet: 'Удалить подход',
    emptyExercises: 'Добавь тренажер выше, затем вноси подходы по одному.',
    exerciseMeta: (setCount: number) => `${setCount} подх.`,
    expandExercise: 'Развернуть тренажер',
    exercisesTitle: 'Упражнения',
    machineAlreadyAdded: (exerciseCount: number, setCount: number) =>
      `${exerciseCount}× · ${setCount} подх.`,
    machineSearchPlaceholder: 'Поиск тренажера',
    noMachinesTitle: 'Тренажеров пока нет',
    noMachinesMessage: 'Сначала добавь тренажеры во вкладке «Тренажеры».',
    repsLabel: 'Повторения',
    repsPlaceholder: 'Повт.',
    sessionTitle: 'Тренировка',
    setNoteLabel: 'Заметка к подходу',
    setNotePlaceholder: 'Заметка к подходу',
    setNumber: (number: number) => `${number}.`,
    startWorkout: 'Начать тренировку',
    unknownDate: 'Дата не указана',
    toggleSetNote: 'Показать заметку к подходу',
    weightLabel: 'Вес, кг',
    weightPlaceholder: 'кг',
  },
  accessibility: {
    addMachine: 'Добавить тренажер',
    addWorkout: 'Добавить тренировку',
    back: 'Назад',
    deleteMachine: 'Удалить тренажер',
    deleteWorkout: 'Удалить тренировку',
    editMachine: 'Редактировать тренажер',
    editWorkout: 'Редактировать тренировку',
    finishWorkout: 'Завершить тренировку',
    openMachinePicker: 'Открыть выбор тренажера',
    repeatWorkout: 'Повторить тренировку',
    settings: 'Открыть настройки',
    search: 'Поиск',
    clearSearch: 'Очистить поиск',
    changeUser: 'Сменить пользователя',
    saveMachine: 'Сохранить тренажер',
    saveWorkout: 'Сохранить тренировку',
    startWorkout: 'Начать тренировку',
    searchMachinesInWorkout: 'Поиск тренажера для тренировки',
  },
  muscleGroups: {
    labels: {
      chest: 'Грудь',
      back: 'Спина',
      shoulders: 'Плечи',
      biceps: 'Бицепс',
      triceps: 'Трицепс',
      forearms: 'Предплечья',
      abs: 'Пресс',
      glutes: 'Ягодицы',
      quads: 'Квадрицепс',
      hamstrings: 'Бицепс бедра',
      calves: 'Икры',
      traps: 'Трапеции',
      adductors: 'Приводящие',
      abductors: 'Отводящие',
      lowerBack: 'Поясница',
    },
    legacyAliases: {
      chest: ['грудь', 'грудные'],
      back: ['спина', 'широчайшие'],
      shoulders: ['плечи', 'дельты'],
      biceps: ['бицепс', 'бицепсы'],
      triceps: ['трицепс', 'трицепсы'],
      forearms: ['предплечья', 'предплечье'],
      abs: ['пресс', 'кор'],
      glutes: ['ягодицы', 'ягодичные'],
      quads: ['квадрицепс', 'квадрицепсы', 'ноги', 'бедра'],
      hamstrings: ['бицепс бедра', 'задняя поверхность бедра'],
      calves: ['икры', 'голени'],
      traps: ['трапеции', 'трапеция'],
      adductors: ['приводящие'],
      abductors: ['отводящие'],
      lowerBack: ['поясница', 'разгибатели спины'],
    },
  },
} as const;
