export const strings = {
  app: {
    title: 'GymBro',
  },
  tabs: {
    machines: 'Тренажеры',
    workouts: 'Тренировки',
  },
  search: {
    machines: 'Поиск тренажера',
    workouts: 'Поиск тренировки',
  },
  empty: {
    machines: {
      title: 'Тренажеров пока нет',
      message: 'Здесь появятся тренажеры, которые ты добавишь для своих занятий.',
    },
    workouts: {
      title: 'Тренировок пока нет',
      message: 'Нажми кнопку внизу, чтобы начать первую тренировку в зале.',
    },
    filtered: {
      title: 'Ничего не найдено',
      message: 'Попробуй изменить запрос или сбросить поиск.',
    },
  },
  actions: {
    cancel: 'Отмена',
    addIcon: '+',
    delete: 'Удалить',
    deleteIcon: '×',
    dontSave: 'Не сохранять',
    editIcon: '✎',
    finish: 'Завершить',
    ok: 'ОК',
    resetSearch: 'Сбросить поиск',
    save: 'Сохранить',
  },
  alerts: {
    deleteMachineTitle: 'Удалить тренажер?',
    deleteMachineMessage: (name: string) =>
      `Тренажер «${name}» будет удален из списка.`,
    deleteWorkoutTitle: 'Удалить тренировку?',
    deleteWorkoutMessage: (name: string) =>
      `Тренировка «${name}» будет удалена из списка.`,
    exitWorkoutTitle: 'Сохранить тренировку?',
    exitWorkoutMessage: 'Перед выходом можно сохранить введенные подходы.',
    storageLoadTitle: 'Не удалось загрузить данные',
    storageLoadMessage: 'Попробуй открыть приложение еще раз.',
    storageSaveTitle: 'Не удалось сохранить данные',
    storageSaveMessage: 'Проверь свободное место на устройстве и попробуй снова.',
  },
  forms: {
    machine: {
      addTitle: 'Новый тренажер',
      editTitle: 'Редактировать тренажер',
      nameLabel: 'Название',
      namePlaceholder: 'Например, жим ногами',
      muscleGroupLabel: 'Группы мышц',
      muscleGroupHint: 'Выбери одну или несколько групп.',
      noteLabel: 'Заметка',
      notePlaceholder: 'Посадка, настройки, важные ощущения',
      errors: {
        nameRequired: 'Введите название тренажера.',
      },
    },
    workout: {
      nameLabel: 'Название',
      namePlaceholder: 'Например, Тренировка ног',
    },
  },
  workouts: {
    addExerciseTitle: 'Добавить тренажер',
    addMachineToWorkout: (name: string) => `Добавить ${name} в тренировку`,
    addSet: 'Добавить подход',
    cardMeta: (exerciseCount: number, setCount: number) =>
      `${exerciseCount} упр. · ${setCount} подх.`,
    collapseExercise: 'Свернуть тренажер',
    defaultName: 'Тренировка',
    defaultNameWithDate: (date: string) => `Тренировка ${date}`,
    deleteExercise: 'Удалить упражнение',
    deleteSet: 'Удалить подход',
    emptyExercises: 'Добавь тренажер выше, затем вноси подходы по одному.',
    exerciseMeta: (setCount: number) => `${setCount} подх.`,
    expandExercise: 'Развернуть тренажер',
    exercisesTitle: 'Упражнения',
    machineAlreadyAdded: (exerciseCount: number, setCount: number) =>
      `${exerciseCount}× · ${setCount} подх.`,
    machineSearchPlaceholder: 'Поиск тренажера',
    noMachinesTitle: 'Тренажеров пока нет',
    noMachinesMessage: 'Сначала добавь тренажеры во вкладке «Тренажеры».',
    repsLabel: 'Повторения',
    repsPlaceholder: 'Повт.',
    sessionTitle: 'Тренировка',
    setNoteLabel: 'Заметка к подходу',
    setNotePlaceholder: 'Заметка к подходу',
    setNumber: (number: number) => `${number}.`,
    startWorkout: 'Начать тренировку',
    unknownDate: 'Дата не указана',
    toggleSetNote: 'Показать заметку к подходу',
    weightLabel: 'Вес, кг',
    weightPlaceholder: 'кг',
  },
  accessibility: {
    addMachine: 'Добавить тренажер',
    addWorkout: 'Добавить тренировку',
    back: 'Назад',
    deleteMachine: 'Удалить тренажер',
    deleteWorkout: 'Удалить тренировку',
    editMachine: 'Редактировать тренажер',
    editWorkout: 'Редактировать тренировку',
    finishWorkout: 'Завершить тренировку',
    repeatWorkout: 'Повторить тренировку',
    settings: 'Открыть настройки',
    search: 'Поиск',
    clearSearch: 'Очистить поиск',
    saveMachine: 'Сохранить тренажер',
    saveWorkout: 'Сохранить тренировку',
    startWorkout: 'Начать тренировку',
    searchMachinesInWorkout: 'Поиск тренажера для тренировки',
  },
  muscleGroups: {
    labels: {
      chest: 'Грудь',
      back: 'Спина',
      shoulders: 'Плечи',
      biceps: 'Бицепс',
      triceps: 'Трицепс',
      forearms: 'Предплечья',
      abs: 'Пресс',
      glutes: 'Ягодицы',
      quads: 'Квадрицепс',
      hamstrings: 'Бицепс бедра',
      calves: 'Икры',
      traps: 'Трапеции',
      adductors: 'Приводящие',
      abductors: 'Отводящие',
      lowerBack: 'Поясница',
    },
    legacyAliases: {
      chest: ['грудь', 'грудные'],
      back: ['спина', 'широчайшие'],
      shoulders: ['плечи', 'дельты'],
      biceps: ['бицепс', 'бицепсы'],
      triceps: ['трицепс', 'трицепсы'],
      forearms: ['предплечья', 'предплечье'],
      abs: ['пресс', 'кор'],
      glutes: ['ягодицы', 'ягодичные'],
      quads: ['квадрицепс', 'квадрицепсы', 'ноги', 'бедра'],
      hamstrings: ['бицепс бедра', 'задняя поверхность бедра'],
      calves: ['икры', 'голени'],
      traps: ['трапеции', 'трапеция'],
      adductors: ['приводящие'],
      abductors: ['отводящие'],
      lowerBack: ['поясница', 'разгибатели спины'],
    },
  },
  standardMachines: {
    legPress: {
      name: 'Жим ногами',
      note: 'Leg press. Платформа для жима ногами сидя или под углом.',
    },
    legExtension: {
      name: 'Разгибание ног',
      note: 'Leg extension. Валик перед голенями, разгибание коленей сидя.',
    },
    seatedLegCurl: {
      name: 'Сгибание ног сидя',
      note: 'Seated leg curl. Сгибание коленей сидя, валик у голеней.',
    },
    lyingLegCurl: {
      name: 'Сгибание ног лежа',
      note: 'Lying leg curl. Сгибание коленей лежа лицом вниз.',
    },
    hipAdduction: {
      name: 'Сведение ног',
      note: 'Adductor. Ноги сводятся внутрь.',
    },
    hipAbduction: {
      name: 'Разведение ног',
      note: 'Abductor. Ноги разводятся наружу.',
    },
    calfRaise: {
      name: 'Подъем на икры',
      note: 'Calf raise. Подъем на носки сидя или стоя.',
    },
    gluteKickback: {
      name: 'Отведение ноги назад',
      note: 'Glute kickback. Нога уходит назад, акцент на ягодицы.',
    },
    chestPress: {
      name: 'Жим от груди',
      note: 'Chest press. Жим рукоятей вперед сидя.',
    },
    inclineChestPress: {
      name: 'Жим от груди в наклоне',
      note: 'Incline chest press. Жим вверх-вперед, акцент на верх груди.',
    },
    pecDeck: {
      name: 'Сведение рук / бабочка',
      note: 'Pec deck или butterfly. Сведение рук перед грудью.',
    },
    shoulderPress: {
      name: 'Жим плечами',
      note: 'Shoulder press. Жим рукоятей вверх сидя.',
    },
    lateralRaise: {
      name: 'Разведение рук в стороны',
      note: 'Lateral raise. Подъем рук в стороны, акцент на средние дельты.',
    },
    latPulldown: {
      name: 'Вертикальная тяга',
      note: 'Lat pulldown. Тяга рукояти сверху к груди.',
    },
    seatedRow: {
      name: 'Горизонтальная тяга',
      note: 'Seated row. Тяга рукояти к животу сидя.',
    },
    highRow: {
      name: 'Рычажная тяга сверху',
      note: 'High row. Рычажная тяга сверху-вниз на спину.',
    },
    machinePullover: {
      name: 'Пуловер в тренажере',
      note: 'Machine pullover. Движение прямыми или полусогнутыми руками сверху вниз.',
    },
    backExtension: {
      name: 'Гиперэкстензия',
      note: 'Back extension. Разгибание корпуса, акцент на поясницу и ягодицы.',
    },
    bicepsCurl: {
      name: 'Сгибание рук на бицепс',
      note: 'Biceps curl machine. Сгибание локтей на тренажере.',
    },
    tricepsExtension: {
      name: 'Разгибание рук на трицепс',
      note: 'Triceps extension или pushdown. Разгибание локтей.',
    },
    assistedPullUpDip: {
      name: 'Гравитрон',
      note: 'Assisted pull-up / dip. Подтягивания или отжимания с противовесом.',
    },
    abdominalCrunch: {
      name: 'Скручивания в тренажере',
      note: 'Abdominal crunch. Сгибание корпуса на пресс.',
    },
    torsoRotation: {
      name: 'Повороты корпуса',
      note: 'Torso rotation. Повороты корпуса сидя, акцент на косые мышцы пресса.',
    },
  },
} as const;
